import { useReducer, useState } from 'react';
import { Activity, ArrowDownToLine, Bot, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, History, Laptop, MessageSquare, MessagesSquare, Monitor, Pause, Play, RefreshCw, Search, ShieldCheck, Wifi, WifiOff } from 'lucide-react';
import { Chat, ConversationList, Details, IconButton, Modal, Toggle } from './components';
import { draftReply, initialState, reducer } from './model';

export default function App() {
  const [state, dispatch] = useReducer(reducer, undefined, initialState);
  const [selected, setSelected] = useState('demo-visitor-01');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [view, setView] = useState<'messages' | 'activity'>('messages');
  const [modal, setModal] = useState<'device' | 'history' | 'image' | 'details' | 'reset' | 'about' | null>(null);
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [mobileChat, setMobileChat] = useState(false);
  const [eventFilter, setEventFilter] = useState('all');
  const [notice, setNotice] = useState('');
  const conversation = state.conversations.find(c => c.id === selected)!;
  const draft = drafts[selected] || '';
  const setDraft = (text: string) => setDrafts(current => ({ ...current, [selected]: text }));
  const unread = state.conversations.reduce((n, c) => n + c.unread, 0);
  function reset() { dispatch({ type: 'reset' }); setSelected('demo-visitor-01'); setQuery(''); setFilter('all'); setDrafts({}); setMobileChat(false); setModal(null); setNotice('演示数据已重置'); }
  function send() { dispatch({ type: 'send', id: selected, text: draft }); setDraft(''); setNotice('回复已发送到本地演示会话'); }
  function incoming() { dispatch({ type: 'receive', id: selected, text: '你好，想确认一下设备离线后如何恢复连接？' }); setNotice(state.recovery ? '恢复期间的新观察仅进入历史' : '已模拟一条新入站消息'); }
  function generateDraft() { const last = [...conversation.messages].reverse().find(m => m.direction === 'inbound' && !m.history); setDraft(draftReply(last?.text || '')); setNotice('已填入演示草稿，可编辑后发送'); }
  const filteredEvents = state.events.filter(event => eventFilter === 'all' || event.kind === eventFilter);
  return <div className="app-shell">
    <header className="app-header"><a className="brand" href="#" onClick={e => { e.preventDefault(); setView('messages'); }}><span className="brand-icon"><MessagesSquare size={22} /></span><span>WeCom <strong>Capture</strong></span></a><div className="header-divider" /><span className="workspace-name">消息运营</span><div className="header-right"><span className="demo-label"><span />演示环境</span><span className="header-user">D</span><span className="user-label">演示坐席</span></div></header>
    <div className="app-body"><nav className="rail" aria-label="主导航"><button className={view === 'messages' ? 'active' : ''} aria-label="消息工作台" title="消息工作台" onClick={() => setView('messages')}><MessageSquare size={21} /><span>消息</span></button><button aria-label="设备管理" title="设备管理" onClick={() => setModal('device')}><Monitor size={21} /><span>设备</span></button><button className={view === 'activity' ? 'active' : ''} aria-label="运行记录" title="运行记录" onClick={() => setView('activity')}><Activity size={21} /><span>记录</span></button><div className="rail-bottom"><button aria-label="关于演示" title="关于演示" onClick={() => setModal('about')}><CircleHelp size={20} /></button></div></nav>
      <main className="main">
        <div className="page-heading"><div><div className="breadcrumb">工作空间<ChevronRight size={12} /><span>{view === 'messages' ? '消息工作台' : '运行记录'}</span></div><h1>{view === 'messages' ? '企微消息工作台' : '运行记录'}<span className="page-count">{view === 'messages' ? `${state.conversations.length} 个会话` : `${state.events.length} 条记录`}</span></h1></div><div className="page-actions"><label className="global-ai"><Bot size={16} />AI 接待<Toggle label="全局 AI 接待" checked={state.globalAi} onChange={() => dispatch({ type: 'toggleGlobalAi' })} /></label><span className="action-divider" /><button className="secondary" onClick={() => setModal('history')}><History size={15} /><span>历史补录</span></button><button className="secondary device-button" onClick={() => setModal('device')}><Laptop size={16} /><span>设备管理</span></button><IconButton label="重置演示" onClick={() => setModal('reset')}><RefreshCw size={16} /></IconButton></div></div>
        <div className={`connection-strip ${!state.online || state.recovery ? 'warning' : ''}`}><span className="connection-main">{state.online ? <Wifi size={15} /> : <WifiOff size={15} />}<strong>{state.recovery ? '历史恢复暂停中' : state.online ? '演示 Mac 已连接' : '演示 Mac 已离线'}</strong><span className="connection-description">{state.recovery ? '历史消息仅入库，发送任务已暂停' : state.online ? '消息接收正常' : '可查看历史消息，发送任务已暂停'}</span></span><button onClick={() => setModal(state.recovery ? 'history' : 'device')}>{state.recovery ? '查看恢复状态' : '查看设备'}<ChevronRight size={13} /></button></div>
        {view === 'messages' ? <div className={`workbench ${mobileChat ? 'show-chat' : ''}`}>
          <ConversationList conversations={state.conversations} selected={selected} onSelect={id => { setSelected(id); dispatch({ type: 'read', id }); setMobileChat(true); }} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} />
          <Chat conversation={conversation} state={state} active={mobileChat} draft={draft} setDraft={setDraft} onSend={send} onToggleAi={() => dispatch({ type: 'toggleAi', id: selected })} onResolve={() => dispatch({ type: 'resolve', id: selected })} onIncoming={incoming} onDraft={generateDraft} onImage={() => setModal('image')} onAttach={() => { dispatch({ type: 'send', id: selected, text: '设备状态示例', image: true }); setNotice('示例图片已发送'); }} onBack={() => setMobileChat(false)} onDetails={() => setModal('details')} />
          <aside className="details" aria-label="会话信息"><div className="details-heading">会话信息<ShieldCheck size={15} /></div><Details conversation={conversation} state={state} /></aside>
        </div> : <section className="activity-view"><div className="activity-heading"><h2>最近活动</h2><select aria-label="筛选运行记录" value={eventFilter} onChange={e => setEventFilter(e.target.value)}><option value="all">全部类型</option><option value="message">消息收发</option><option value="device">设备连接</option><option value="recovery">历史恢复</option><option value="setting">接待设置</option></select></div><div className="table-wrap"><table><thead><tr><th>时间</th><th>事件</th><th>详情</th><th>环境</th></tr></thead><tbody>{filteredEvents.map(event => <tr key={event.id}><td><Clock3 size={13} />{event.time}</td><td>{event.title}</td><td>{event.detail}</td><td><span className="table-badge">本地演示</span></td></tr>)}</tbody></table>{!filteredEvents.length && <div className="empty"><Search /><strong>暂无此类记录</strong></div>}</div></section>}
        <footer className="app-footer"><span><span className="status-dot" />本地演示 · 无真实消息发送</span><span>{unread} 条未读<span className="separator">/</span>{state.conversations.filter(c => c.ai).length} 个 AI 托管会话</span></footer>
      </main>
    </div>
    <div className="sr-only" role="status" aria-live="polite">{notice}</div>
    {modal === 'device' && <Modal title="设备管理" onClose={() => setModal(null)}><div className="device-overview"><span className="device-illustration"><Laptop size={38} /></span><div><h3>演示 Mac</h3><p>虚构设备 · macOS</p></div><span className={`badge ${state.online ? 'green' : 'gray'}`}>{state.online ? '在线' : '离线'}</span></div><dl className="device-spec"><dt>设备编号</dt><dd>demo-mac-01</dd><dt>辅助功能</dt><dd><CheckCircle2 size={14} />模拟已授权</dd><dt>屏幕录制</dt><dd><CheckCircle2 size={14} />模拟已授权</dd><dt>接收状态</dt><dd>{state.recovery ? '恢复暂停' : state.online ? '就绪' : '已暂停'}</dd></dl><div className="dialog-notice"><ShieldCheck size={16} />演示设备不连接真实电脑或企微账号。</div><footer><button className="secondary" onClick={() => dispatch({ type: 'toggleOnline' })}>{state.online ? <WifiOff size={15} /> : <Wifi size={15} />}{state.online ? '模拟设备离线' : '恢复设备连接'}</button><button className="primary" onClick={() => setModal(null)}>完成</button></footer></Modal>}
    {modal === 'history' && <Modal title="历史补录" onClose={() => setModal(null)} wide><div className="recovery-summary"><span className="recovery-icon"><History size={24} /></span><div><h3>{state.recovery ? '历史记录已收录，等待恢复接收' : '补录历史会话'}</h3><p>{state.recovery ? '3 个会话 · 6 条示例消息 · 0 条 AI 回复' : '将虚构历史记录加入以下会话'}</p></div><span className={`badge ${state.recovery ? 'amber' : 'green'}`}>{state.recovery ? '发送暂停' : '准备就绪'}</span></div><div className="recovery-list">{state.conversations.slice(0, 3).map(c => <div key={c.id}><span className={`avatar small ${c.color}`}>{c.avatar}</span><strong>{c.name}</strong><span>{state.recovery ? '2 条历史消息' : '2 条示例记录'}</span>{state.recovery ? <CheckCircle2 size={17} className="success-icon" /> : <Clock3 size={17} />}</div>)}</div><div className="dialog-notice"><ShieldCheck size={17} /><span>补录消息只进入历史，不触发 AI 回复或人工接管。结束恢复不会补发旧任务。</span></div><footer><button className="secondary" onClick={() => setModal(null)}>关闭</button><button className="primary" disabled={!state.online && !state.recovery} onClick={() => dispatch({ type: state.recovery ? 'endRecovery' : 'beginRecovery' })}>{state.recovery ? <Play size={15} /> : <ArrowDownToLine size={15} />}{state.recovery ? '结束恢复并继续接收' : '开始演示补录'}</button></footer></Modal>}
    {modal === 'image' && <Modal title="设备状态示例" wide onClose={() => setModal(null)}><img className="image-preview" src={`${import.meta.env.BASE_URL}device-sample.png`} alt="虚构设备状态详情，无真实账号信息" /><div className="image-caption">演示附件 · 虚构设备与状态</div></Modal>}
    {modal === 'details' && <Modal title="会话信息" onClose={() => setModal(null)}><Details conversation={conversation} state={state} /></Modal>}
    {modal === 'reset' && <Modal title="重置演示数据" onClose={() => setModal(null)}><p className="dialog-copy">将清除本次演示中的回复、补录和设置变化，恢复初始虚构会话。</p><footer><button className="secondary" onClick={() => setModal(null)}>取消</button><button className="primary" onClick={reset}><RefreshCw size={15} />确认重置</button></footer></Modal>}
    {modal === 'about' && <Modal title="关于演示" onClose={() => setModal(null)}><div className="about-mark"><MessagesSquare size={34} /><h3>WeCom Capture</h3></div><p className="dialog-copy">本工作台使用虚构联系人、消息、设备和预设回复，仅在当前浏览器内运行。没有调用模型、连接设备或发送真实消息。</p><p className="dialog-copy">刷新页面或重置演示会恢复初始数据。</p><footer><button className="primary" onClick={() => setModal(null)}><Check size={16} />知道了</button></footer></Modal>}
  </div>;
}
